# .github/workflows/sync.yml
name: Sync to repo with separate pages (go.emeland.io)
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.gihub/actions/setup-git-sync
      with:
        mirror-ssh-key: ${{ secrets.MIRROR_REPO_SSH_KEY }}
    - uses: actions/checkout@v6
    - run: |
        git remote add public git@github-mirror:go-emeland-io2/go-libraries.git
        git push public main
